<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="frmMenuUsuario.aspx.cs" Inherits="ArvoProjectWebsite.WebForms.frmMenuUsuario" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title></title>
</head>
<body>
    <form id="form1" runat="server">
        <p>
            &nbsp;</p>
        <p>
            &nbsp;</p>
        <p>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; MENÚ USUARIO</p>
        <p>
            <asp:Label ID="lblNombreMenuUsuario" runat="server"></asp:Label>
        </p>
        <p>
            &nbsp;DNI:&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            <asp:Label ID="lblDniMenuUsuario" runat="server"></asp:Label>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
&nbsp;&nbsp;&nbsp;
            <asp:LinkButton  ID="lbtnModificarDniMenuUsuario" runat="server" >Modificar</asp:LinkButton>
        </p>
        <p>
            MAIL:&nbsp;&nbsp;&nbsp; <asp:Label ID="lblMailMenuUsuario" runat="server"></asp:Label>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            <asp:LinkButton ID="lbtnModificarMailMenuUsuario" runat="server">Modificar</asp:LinkButton>
        </p>
        <p>
            Direcciones</p>
        <p>
            <asp:GridView ID="grdDireccionesMenuUsuarios" runat="server" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True">
            </asp:GridView>
&nbsp;&nbsp;&nbsp;
            <asp:Button ID="btnAgregarDireccionesMenuUsuarios" runat="server" Text="Agregar" />
&nbsp;&nbsp;&nbsp;
            <asp:Button ID="btnEliminarMenuUsuarios" runat="server" Text="Eliminar" />
        </p>
        <p>
            Metodos de Pago</p>
        <p>
            <asp:GridView ID="grdMdePagoMenuUsuarios" runat="server" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True">
            </asp:GridView>
&nbsp;&nbsp;&nbsp;
            <asp:Button ID="btnAgregarMdPagoMenuUsuarios" runat="server" Text="Agregar" />
&nbsp;&nbsp;&nbsp;
            <asp:Button ID="btnEliminarMdePagoMenuUsuarios" runat="server" Text="Eliminar" />
        </p>
        <p>
            Compras</p>
        <p>
            <asp:GridView ID="grdComprasMenuUsuarios" runat="server" AutoGenerateColumns="False" AutoGenerateSelectButton="True" DataSourceID="SqlDataSource1">
                <Columns>
                    <asp:ImageField DataImageUrlField= "RutaImagen">
                    </asp:ImageField>
                    <asp:BoundField DataField="RutaImagen" HeaderText="RutaImagen" SortExpression="RutaImagen" />
                    <asp:BoundField DataField="IDProducto_DETV" HeaderText="IDProducto_DETV" SortExpression="IDProducto_DETV" />
                    <asp:BoundField DataField="Cantidad_DETV" HeaderText="Cantidad_DETV" SortExpression="Cantidad_DETV" />
                    <asp:BoundField DataField="PrecioUnitario_DETV" HeaderText="PrecioUnitario_DETV" SortExpression="PrecioUnitario_DETV" />
                    <asp:BoundField DataField="Descuento_DETV" HeaderText="Descuento_DETV" SortExpression="Descuento_DETV" />
                    <asp:BoundField DataField="IDVenta" HeaderText="IDVenta" InsertVisible="False" ReadOnly="True" SortExpression="IDVenta" />
                    <asp:BoundField DataField="Total_VENTA" HeaderText="Total_VENTA" SortExpression="Total_VENTA" />
                </Columns>
            </asp:GridView>
            <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:ComprasoBDConnectionString %>" SelectCommand="select RTRIM(RutaImagen) AS RutaImagen,IDProducto_DETV,Cantidad_DETV, PrecioUnitario_DETV, Descuento_DETV,IDVenta ,Total_VENTA  from VENTAS inner join DETVENTAS on IDVenta = IDVenta_DETV
inner join PRODUCTOS on IDProducto_DETV = IDProducto
where IDUsuario_VENTA = '0000'"></asp:SqlDataSource>
        </p>
        <p>
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            <asp:Button ID="btnCancelarCompraMenuUsuarios" runat="server" Text="Cancelar" />
        </p>
    </form>
</body>
</html>
