<%@ Page Title="" Language="C#" MasterPageFile="~/WebForms/MasterPage.Master" AutoEventWireup="true" CodeBehind="frmMenuUsuario.aspx.cs" Inherits="ArvoProjectWebsite.WebForms.frmMenuUsuario" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <p>
        MENÚ USUARIO</p>
    <p>
        <asp:Label ID="lblNombreMenuUsuario" runat="server"></asp:Label>
    </p>
    <p>
        DNI:&nbsp;&nbsp;&nbsp;&nbsp;
        <asp:Label ID="lblDniMenuUsuario" runat="server"></asp:Label>
    </p>
    <p>
        EMAIL:&nbsp;&nbsp;&nbsp;
        <asp:Label ID="lblMailMenuUsuario" runat="server"></asp:Label>
    </p>
    <p>
        <asp:LinkButton ID="lbtnDireccionesMenuUsuario" runat="server" OnClick="lbtnDireccionesMenuUsuario_Click">Direcciones</asp:LinkButton>
&nbsp;&nbsp;&nbsp;
        <asp:LinkButton ID="lbtnMdPMenuUsuario" runat="server" OnClick="lbtnMdPMenuUsuario_Click">Medios de Pago</asp:LinkButton>
&nbsp;&nbsp;&nbsp;
        <asp:LinkButton ID="lbtnComprasMenuUsuario" runat="server" OnClick="lbtnComprasMenuUsuario_Click">Compras</asp:LinkButton>
    </p>
    <p>
        <asp:Label ID="lblMenuUsuario" runat="server"></asp:Label>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    </p>
    <p>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        <asp:GridView ID="grdMenuUsuario" horizontalalign="Center" runat="server" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" CellPadding="15" OnSelectedIndexChanged="grdMenuUsuario_SelectedIndexChanged" OnRowDeleted="grdMenuUsuario_RowDeleted" OnRowEditing="grdMenuUsuario_RowEditing">
            <EditRowStyle BackColor="#3366FF" />
        </asp:GridView>
    </p>
</asp:Content>
