using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;
using CapaLogicadeNegocio;
using Entidad;
using System.Data.SqlClient;
using System.Data;

namespace ArvoProjectWebsite.WebForms
{
    public partial class frmMenuUsuario : System.Web.UI.Page
    {
        protected void Page_Load(object sender, EventArgs e)
        {
            gestionUsuarios gestionUsuarios = new gestionUsuarios();
            //Usuario usu = new Usuario();
            //usu.IDUsuario = "0000";
            //Application["Usuario"] = usu;

            lblDniMenuUsuario.Text = ((Usuario)Application["Usuario"]).DNI;
            lblMailMenuUsuario.Text = ((Usuario)Application["Usuario"]).Email;
            lblNombreMenuUsuario.Text = ((Usuario)Application["Usuario"]).Apellido + " " + ((Usuario)Application["Usuario"]).Nombre;

            grdMenuUsuario.Visible = true;
            grdMenuUsuario.AutoGenerateSelectButton = false;
            grdMenuUsuario.AutoGenerateDeleteButton = true;
            ddlCampo2.Visible = false;
            lblCampo2.Visible = false;
            lblCampo1.Visible = false;
            lblCampo3.Visible = false;
            lblCampo4.Visible = false;
            lblSeparadorVenc.Visible = false;
            txtCampo1.Visible = false;
            txtCampo3.Visible = false;
            txtCampo4.Visible = false;;
            txtCampo4b.Visible = false;
            lbtnAceptar.Visible = false;
            lblValidarTarjeta.Visible = false;
            lblValidarUsuario.Visible = false;
            lblValidarVencimiento.Visible = false;
            //lbtnAgregarMenuUsuario.Visible = true;

            if (!IsPostBack)
            {
                
            }
        }

        protected void lbtnDireccionesMenuUsuario_Click(object sender, EventArgs e)
        {
            lblMenuUsuario.Text = "Direcciones";
            lbtnAgregarMenuUsuario.Visible = true;
            gestionUsuarios gestionUsuarios = new gestionUsuarios();

            Session["Direcciones"] = gestionUsuarios.CargarDirecciones((Usuario)Application["Usuario"]);
            grdMenuUsuario.DataSource = Session["Direcciones"];
            grdMenuUsuario.DataBind();

            DataTable Tabla = gestionUsuarios.getDropDrownUsuario("Provincias");
                //ddlCampo2.Visible = true;
                ddlCampo2.DataSource = Tabla;
                ddlCampo2.DataTextField = "Provincia_ENVIO";
                ddlCampo2.DataValueField = null;
                ddlCampo2.DataBind();
        }

        protected void lbtnMdPMenuUsuario_Click(object sender, EventArgs e)
        {
            lblMenuUsuario.Text = "Medios de Pago";
            lbtnAgregarMenuUsuario.Visible = true;
            gestionUsuarios gestionUsuarios = new gestionUsuarios();

            Session["MdP"] = gestionUsuarios.CargarMdPxUsu((Usuario)Application["Usuario"]);
            grdMenuUsuario.DataSource = Session["MdP"];
            grdMenuUsuario.DataBind();

            DataTable Tabla = gestionUsuarios.getDropDrownUsuario("Tarjetas");
            ddlCampo2.DataSource = Tabla;
            ddlCampo2.DataTextField = "Nombre_TARJ";
            ddlCampo2.DataValueField = "IDTarjeta_TARJ";
            ddlCampo2.DataBind();
        }

        protected void lbtnComprasMenuUsuario_Click(object sender, EventArgs e)
        {
            lblMenuUsuario.Text = "Compras";
            lbtnAgregarMenuUsuario.Visible = false;
            grdMenuUsuario.AutoGenerateSelectButton = true;

            gestionUsuarios gestionUsuarios = new gestionUsuarios();
            Session["Compras"] = gestionUsuarios.CargarTablaCompras(((Usuario)Application["Usuario"]));
            grdMenuUsuario.DataSource = Session["Compras"];
            grdMenuUsuario.DataBind();
        }


        protected void grdMenuUsuario_RowDeleting(object sender, GridViewDeleteEventArgs e)
        {
            gestionUsuarios gestionUsuarios = new gestionUsuarios();

            switch (lblMenuUsuario.Text)
            {
                case "Compras":
                    if (((DataTable)Session["Compras"]).Rows[e.RowIndex][7].ToString() == "Procesando")
                    {
                        gestionUsuarios.CancelarCompra((int)((DataTable)Session["Compras"]).Rows[e.RowIndex][0]);
                        Session["Compras"] = gestionUsuarios.CargarTablaCompras((Usuario)Application["Usuario"]);
                        grdMenuUsuario.DataSource = Session["Compras"];
                        grdMenuUsuario.DataBind();

                    }
                    else
                    {
                        lblDniMenuUsuario.Text = ((DataTable)Session["Compras"]).Rows[e.RowIndex][7].ToString();
                    }
                    break;
                case "Medios de Pago":
                                       Session["MdP"] = gestionUsuarios.CargarMdPxUsu((Usuario)Application["Usuario"]);
                                       gestionUsuarios.EliminarMediodePagoxUsu((Usuario)Application["Usuario"], ((DataTable)Session["MdP"]).Rows[e.RowIndex][1].ToString(),
                                       ((DataTable)Session["Mdp"]).Rows[e.RowIndex][0].ToString());
                                       Session["MdP"] = gestionUsuarios.CargarMdPxUsu((Usuario)Application["Usuario"]);
                                       grdMenuUsuario.DataSource = Session["MdP"];
                                       grdMenuUsuario.DataBind();
                    break;
                case "Direcciones":
                                    Session["Direcciones"] = gestionUsuarios.CargarDirecciones((Usuario)Application["Usuario"]);
                                    gestionUsuarios.EliminarDireccion((Usuario)Application["Usuario"], (Convert.ToInt32(((DataTable)Session["Direcciones"]).Rows[e.RowIndex][0])));
                                    Session["Direcciones"] = gestionUsuarios.CargarDirecciones((Usuario)Application["Usuario"]);
                                    grdMenuUsuario.DataSource = Session["Direcciones"];
                                    grdMenuUsuario.DataBind();
                    break;
            }
            
        }

        protected void lbtnAgregarMenuUsuario_Click(object sender, EventArgs e)
        {
            gestionUsuarios gestionUsuarios = new gestionUsuarios();
            txtCampo1.Text = "";
            txtCampo3.Text = "";
            txtCampo4.Text = "";
            txtCampo4b.Text = "";
            if (lblMenuUsuario.Text == "Direcciones")
            {
                lbtnAgregarMenuUsuario.Visible = false;
                lblCampo1.Visible = true;
                lblCampo2.Visible = true;
                grdMenuUsuario.Visible = false;
                lblCampo1.Text = "Calle y Número: ";
                txtCampo1.Visible = true;
                txtCampo1.MaxLength = 30;
                lblCampo2.Text = "Provincia: ";
                ddlCampo2.Visible = true;
                lbtnAceptar.Visible = true;
                
            }
            else if(lblMenuUsuario.Text == "Medios de Pago")
            {
                lbtnAgregarMenuUsuario.Visible = false;
                lblCampo1.Visible = true;
                lblCampo2.Visible = true;
                lblCampo3.Visible = true;
                lblCampo4.Visible = true;
                ddlCampo2.Visible = true;
                grdMenuUsuario.Visible = false;
                lblCampo1.Text = "Número de tarjeta: ";
                txtCampo1.Visible = true;
                txtCampo1.MaxLength = 16;
                txtCampo3.Visible = true;
                lblCampo2.Text = "Tarjeta: ";
                lblCampo3.Text = "Titular: ";
                lblSeparadorVenc.Visible = true;
                lblCampo4.Text = "Vencimiento: ";
                txtCampo4.Visible = true;
                txtCampo4b.Visible = true;
                lbtnAceptar.Visible = true;
            }
        }

        protected void lbtnAceptar_Click(object sender, EventArgs e)
        {
            gestionUsuarios gestionUsuarios = new gestionUsuarios();
            Usuario usu = (Usuario)Application["Usuario"];
            lbtnAgregarMenuUsuario.Visible = true;
            bool guardar = true;
            if (lblMenuUsuario.Text == "Direcciones")
            {
                //
                lbtnAgregarMenuUsuario.Visible = false;
                lblCampo1.Visible = true;
                lblCampo2.Visible = true;
                grdMenuUsuario.Visible = false;
                lblCampo1.Text = "Calle y Número: ";
                txtCampo1.Visible = true;
                txtCampo1.MaxLength = 30;
                lblCampo2.Text = "Provincia: ";
                ddlCampo2.Visible = true;
                lbtnAceptar.Visible = true;

                //VALIDA QUE LA DIRECCION NO ESTE VACIA
                if(txtCampo1.Text.Length == 0)
                {
                    lblValidarTarjeta.Text = "La dirección no puede estar vacia.";
                    lblValidarTarjeta.Visible = true;
                    guardar = false;
                }

                //VALIDA QUE TENGA LETRAS
                if (!Utilidades.ContieneLetras(txtCampo1.Text, txtCampo1.Text.Length))
                {
                    lblValidarTarjeta.Text = "La dirección debe incluir el nombre de la calle.";
                    lblValidarTarjeta.Visible = true;
                    guardar = false;
                }
                //VALIDA QUE TENGA NUMEROS
                if (!Utilidades.ContieneNumeros(txtCampo1.Text, txtCampo1.Text.Length))
                {
                    lblValidarTarjeta.Text = "La dirección debe incluir el número.";
                    lblValidarTarjeta.Visible = true;
                    guardar = false;
                }
                
                //
                if (guardar)
                {
                    gestionUsuarios.AgregarDireccion(usu.IDUsuario, ddlCampo2.Text, txtCampo1.Text);
                    Session["Direcciones"] = gestionUsuarios.Direcciones_x_Usuario((Usuario)Application["Usuario"]);
                    grdMenuUsuario.DataSource = Session["Direcciones"];
                    grdMenuUsuario.DataBind();

                    //
                    grdMenuUsuario.Visible = true;
                    grdMenuUsuario.AutoGenerateSelectButton = false;
                    grdMenuUsuario.AutoGenerateDeleteButton = true;
                    ddlCampo2.Visible = false;
                    lblCampo2.Visible = false;
                    lblCampo1.Visible = false;
                    lblCampo3.Visible = false;
                    lblCampo4.Visible = false;
                    lblSeparadorVenc.Visible = false;
                    txtCampo1.Visible = false;
                    txtCampo3.Visible = false;
                    txtCampo4.Visible = false; ;
                    txtCampo4b.Visible = false;
                    lbtnAceptar.Visible = false;
                    lblValidarTarjeta.Visible = false;
                    lblValidarUsuario.Visible = false;
                    lblValidarVencimiento.Visible = false;
                    lbtnAgregarMenuUsuario.Visible = true;
                    //
                }

            }
            else if (lblMenuUsuario.Text == "Medios de Pago")
            {
                //
                lbtnAgregarMenuUsuario.Visible = false;
                lblCampo1.Visible = true;
                lblCampo2.Visible = true;
                lblCampo3.Visible = true;
                lblCampo4.Visible = true;
                ddlCampo2.Visible = true;
                grdMenuUsuario.Visible = false;
                lblCampo1.Text = "Número de tarjeta: ";
                txtCampo1.Visible = true;
                txtCampo1.MaxLength = 16;
                txtCampo3.Visible = true;
                lblCampo2.Text = "Tarjeta: ";
                lblCampo3.Text = "Titular: ";
                lblSeparadorVenc.Visible = true;
                lblCampo4.Text = "Vencimiento: ";
                txtCampo4.Visible = true;
                txtCampo4b.Visible = true;
                lbtnAceptar.Visible = true;
                //
                //VALIDA QUE LA TARJETA TENGA 16 DIGITOS
                if (txtCampo1.Text.Length < 16)
                {
                    lblValidarTarjeta.Text = "El código de la tarjeta debe ser de 16 números.";
                    lblValidarTarjeta.Visible = true;
                    guardar = false;
                }
                //VALIDA QUE LA TARJETA NO TENGA LETRAS
                if (Utilidades.ContieneLetras(txtCampo1.Text, txtCampo1.Text.Length))
                {
                    lblValidarTarjeta.Text = "No se pueden ingresar letras en el Número de Tarjeta.";
                    lblValidarTarjeta.Visible = true;
                    guardar = false;
                }
                //VALIDA QUE EL TITULAR NO ESTE VACIO
                if(txtCampo3.Text.Length == 0)
                {
                    lblValidarUsuario.Text = "Debe ingresar el nombre del titular de la tarjeta.";
                    lblValidarUsuario.Visible = true;
                    guardar = false;
                }
                //VALIDA QUE EL TITULAR NO CONTENGA NUMEROS
                if (Utilidades.ContieneNumeros(txtCampo3.Text, txtCampo3.Text.Length))
                {
                    lblValidarUsuario.Text = "No se pueden ingresar números en el Titular.";
                    lblValidarUsuario.Visible = true;
                    guardar = false;
                }
                //VALIDA QUE LA FECHA DE VENCIMIENTO NO TENGA LETRAS
                if (Utilidades.ContieneLetras(txtCampo4.Text, txtCampo4.Text.Length) || Utilidades.ContieneLetras(txtCampo4b.Text, txtCampo4b.Text.Length))
                {
                    lblValidarVencimiento.Text = "No se pueden ingresar letras en la Fecha de Vencimiento. ";
                    lblValidarVencimiento.Visible = true;
                    guardar = false;
                }
                //VALIDA QUE EL VENCIMIENTO NO ESTE VACIO
                if (string.IsNullOrEmpty(txtCampo4.Text) || string.IsNullOrEmpty(txtCampo4b.Text))
                {
                    lblValidarVencimiento.Text = "No puede haber campos vacios en el vencimiento.";
                    lblValidarVencimiento.Visible = true;
                    guardar = false;
                }
                
                //VALIDA QUE EL MES NO SEA SUPERIOR A 12
                if (txtCampo4.Text.Length > 0 && !Utilidades.ContieneLetras(txtCampo4.Text, txtCampo4.Text.Length))
                {
                    if (int.Parse(txtCampo4.Text) > 12)
                    {
                        lblValidarVencimiento.Text = "El mes no puede exceder el número 12.";
                        lblValidarVencimiento.Visible = true;
                        guardar = false;
                    }
                }
                if (!Utilidades.ContieneLetras(txtCampo4.Text, txtCampo4.Text.Length))
                {
                    if (txtCampo4.Text.Length == 1) txtCampo4.Text = "0" + txtCampo4.Text;
                }

                //VALIDA QUE EL AÑO NO SEA SUPERIOR A 2030
                if (txtCampo4b.Text.Length > 0 && !Utilidades.ContieneLetras(txtCampo4b.Text,txtCampo4b.Text.Length))
                {
                    if (int.Parse(txtCampo4b.Text) > 2030)
                    {
                        lblValidarVencimiento.Text = "El año no puede ser superior a 2030.";
                        lblValidarVencimiento.Visible = true;
                        guardar = false;
                    }
                }
                //VALIDA QUE EL AÑO TENGA 4 DIGITOS
                if(txtCampo4b.Text.Length <4)
                {
                    lblValidarVencimiento.Text = "El año debe ser de 4 números.";
                    lblValidarVencimiento.Visible = true;
                    guardar = false;
                }

                if (guardar)
                {
                    string vencimiento = txtCampo4b.Text + txtCampo4.Text + "01";;
                    string error = gestionUsuarios.AgregarMdP(usu.IDUsuario, txtCampo1.Text, ddlCampo2.SelectedValue, txtCampo3.Text, vencimiento);
                    Session["MdP"] = gestionUsuarios.CargarMdPxUsu(usu);
                    grdMenuUsuario.DataSource = Session["MdP"];
                    grdMenuUsuario.DataBind();
                    //lbtnAgregarMenuUsuario.Text = error;
                    //
                    grdMenuUsuario.Visible = true;
                    grdMenuUsuario.AutoGenerateSelectButton = false;
                    grdMenuUsuario.AutoGenerateDeleteButton = true;
                    ddlCampo2.Visible = false;
                    lblCampo2.Visible = false;
                    lblCampo1.Visible = false;
                    lblCampo3.Visible = false;
                    lblCampo4.Visible = false;
                    lblSeparadorVenc.Visible = false;
                    txtCampo1.Visible = false;
                    txtCampo3.Visible = false;
                    txtCampo4.Visible = false; ;
                    txtCampo4b.Visible = false;
                    lbtnAceptar.Visible = false;
                    lblValidarTarjeta.Visible = false;
                    lblValidarUsuario.Visible = false;
                    lblValidarVencimiento.Visible = false;
                    lbtnAgregarMenuUsuario.Visible = true;
                    //

                }
            }
        }

        protected void grdMenuUsuario_SelectedIndexChanging(object sender, GridViewSelectEventArgs e)
        {
            lblMenuUsuario.Text = "Detalle de Venta";
            gestionUsuarios gestionUsuarios = new gestionUsuarios();
            grdMenuUsuario.DataSource = gestionUsuarios.ObtenerDetalleVenta(Convert.ToInt32(((DataTable)Session["Compras"]).Rows[e.NewSelectedIndex][0]));
            grdMenuUsuario.AutoGenerateDeleteButton = false;
            grdMenuUsuario.DataBind();
        }
    }
}